=== NexerG/Project-Aurora/AuroraEditor/Data/XML/Schemas/SystemsTypeSchema.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:types="http://arctisaurora/AuroraSystemsTypes" xmlns:actions="http://arctisaurora/ActionDependencies" xmlns:allTypes="http://arctisaurora/AuroraTypes" elementFormDefault="qualified" targetNamespace="http://arctisaurora/AuroraSystemsTypes" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:import schemaLocation="actionSchema.xsd" namespace="http://arctisaurora/ActionDependencies" />
  <xs:import schemaLocation="AllTypesSchema.xsd" namespace="http://arctisaurora/AuroraTypes" />
  <xs:attributeGroup name="Step.Attributes">
    <xs:attribute name="Action" type="xs:string" />
    <xs:attribute name="Edge" type="xs:string" />
    <xs:attribute name="Pinned" type="xs:boolean" />
    <xs:attribute name="Reads" type="xs:string" />
    <xs:attribute name="Writes" type="xs:string" />
  </xs:attributeGroup>
  <xs:element name="Step" type="types:Step" />
  <xs:complexType name="Step">
    <xs:sequence />
    <xs:attributeGroup ref="types:Step.Attributes" />
  </xs:complexType>
  <xs:attributeGroup name="Dedicated.Attributes">
    <xs:attribute name="System" type="xs:string" />
  </xs:attributeGroup>
  <xs:element name="Dedicated" type="types:Dedicated" />
  <xs:complexType name="Dedicated">
    <xs:sequence />
    <xs:attributeGroup ref="types:Dedicated.Attributes" />
  </xs:complexType>
  <xs:element name="FrameGraph" type="types:FrameGraph" />
  <xs:complexType name="FrameGraph">
    <xs:sequence>
      <xs:element minOccurs="0" maxOccurs="unbounded" name="Dedicated" type="types:Dedicated">
        <xs:annotation>
          <xs:documentation></xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element minOccurs="0" maxOccurs="unbounded" name="Step" type="types:Step">
        <xs:annotation>
          <xs:documentation></xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:element name="Main" type="types:Main" />
  <xs:complexType name="Main">
    <xs:sequence />
  </xs:complexType>
  <xs:element name="Physics" type="types:Physics" />
  <xs:complexType name="Physics">
    <xs:sequence />
  </xs:complexType>
  <xs:element name="Render" type="types:Render" />
  <xs:complexType name="Render">
    <xs:sequence />
  </xs:complexType>
  <xs:element name="Animation" type="types:Animation" />
  <xs:complexType name="Animation">
    <xs:sequence />
  </xs:complexType>
</xs:schema>

=== NexerG/Project-Aurora/AuroraEngine/Data/XML/Documents/Frame.frame.xml
<FrameGraph xmlns="http://arctisaurora/AuroraSystemsTypes"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://arctisaurora/AuroraSystemsTypes ../Schemas/SystemsTypeSchema.xsd">

	<Dedicated System="Render"/>

	<Step Action="Main.Input" Pinned="true" Writes="UIElements UIQuads Entities Gradients Effects Animations Paints Signals"/>
	<Step Action="Main.Logic" Pinned="true" Writes="UIElements UIQuads Entities Gradients Effects Animations Paints Signals AnimationDone"/>
	<Step Action="Animation.Step" Reads="Signals Keyframes" Writes="Animations Paints UIElements.ArrangeData UIElements.LayoutNode UIElements.VulkanControl LayoutDirty AnimationDone"/>
	<Step Action="Physics.Step" Writes="Entities.TransformData"/>
	<Step Edge="UIElements" Pinned="true"/>
	<Step Edge="LayoutDirty" Pinned="true"/>
	<Step Action="Main.Layout" Pinned="true" Writes="UIElements UIQuads Entities Gradients Effects Animations Paints LayoutDirty"/>

	<Step Edge="UIQuads" Pinned="true"/>
	<Step Edge="Entities" Pinned="true"/>
	<Step Edge="Gradients" Pinned="true"/>
	<Step Edge="Effects" Pinned="true"/>
	<Step Edge="Paints" Pinned="true"/>
	<Step Edge="Animations" Pinned="true"/>
	<Step Edge="AnimationDone" Pinned="true"/>

	<Step Action="Main.DrawLists" Pinned="true" Writes="UIElements UIQuads Entities Gradients Effects Animations Paints"/>

</FrameGraph>
