=== NexerG/Project-Aurora/Thorium/Data/XML/Schemas/TestTypeSchema.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:types="http://arctisaurora/AuroraTestTypes" xmlns:actions="http://arctisaurora/ActionDependencies" xmlns:allTypes="http://arctisaurora/AuroraTypes" elementFormDefault="qualified" targetNamespace="http://arctisaurora/AuroraTestTypes" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:import schemaLocation="actionSchema.xsd" namespace="http://arctisaurora/ActionDependencies" />
  <xs:import schemaLocation="AllTypesSchema.xsd" namespace="http://arctisaurora/AuroraTypes" />
  <xs:attributeGroup name="Test.Attributes">
    <xs:attribute name="Action" type="actions:Test" />
    <xs:attribute name="Timeout" type="xs:int" />
  </xs:attributeGroup>
  <xs:element name="Test" type="types:Test" />
  <xs:complexType name="Test">
    <xs:sequence />
    <xs:attributeGroup ref="types:Test.Attributes" />
  </xs:complexType>
  <xs:element name="TestSuite" type="types:TestSuite" />
  <xs:complexType name="TestSuite">
    <xs:sequence>
      <xs:element minOccurs="0" maxOccurs="unbounded" name="Test" type="types:Test">
        <xs:annotation>
          <xs:documentation></xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
</xs:schema>

=== NexerG/Project-Aurora/Thorium/Data/XML/Documents/Tests/TextInput.tests.xml
<?xml version="1.0" encoding="utf-8" ?>
<TestSuite xmlns="http://arctisaurora/AuroraTestTypes"
		  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		  xsi:schemaLocation="http://arctisaurora/AuroraTestTypes ../../Schemas/TestTypeSchema.xsd" >
	<Test Action="TextInput.TypeWritesText"/>
	<Test Action="TextInput.WordMoves"/>
	<Test Action="TextInput.UndoReselects"/>
	<Test Action="TextInput.PasteRoundTrip"/>
	<Test Action="TextInput.PastePlainLines"/>
	<Test Action="TextInput.FieldClipboardAndUndo"/>
	<Test Action="TextInput.FieldWordAndScroll"/>
	<Test Action="RegexText.LinesAndCommit"/>
	<Test Action="RegexText.WrapMoves"/>
	<Test Action="RegexText.CommaPattern"/>
	<Test Action="TextInput.DragMovesText"/>
	<Test Action="TextInput.DropOntoRule"/>
	<Test Action="TextInput.DragBetweenNotes"/>
	<Test Action="TextInput.WheelZoom"/>
	<Test Action="TextInput.RightModifiers"/>
	<Test Action="TextInput.StyleSurvivesEnterAndBackspace"/>
	<Test Action="TextInput.UnderlineToggles"/>
	<Test Action="TextInput.MixedSelectionToggles"/>
	<Test Action="TextInput.HighlightApplies"/>
	<Test Action="TextInput.DecorationsDraw"/>
	<Test Action="TextInput.ColorPickerPicks"/>
	<Test Action="TextInput.MarkdownColourRoundTrip"/>
	<Test Action="TextInput.ListMarkersPerList"/>
	<Test Action="TextInput.EmptyItemEnterOutdents"/>
	<Test Action="TextInput.ListMarkersDraw"/>
	<Test Action="TextInput.TableEnterAddsLine"/>
	<Test Action="TextInput.TableTabStepsCells"/>
	<Test Action="TextInput.TableLeftCrossesCells"/>
	<Test Action="TextInput.TableBackspaceKeepsCells"/>
	<Test Action="TextInput.TableWideScrolls"/>
	<Test Action="TextInput.TableXmlRoundTrip"/>
	<Test Action="TextInput.TableDraws"/>
	<Test Action="TextInput.TableOverflowDraws"/>
	<Test Action="TextInput.TableWheelAxes"/>
	<Test Action="TextInput.TableSplitsAcrossPages"/>
	<Test Action="TextInput.TableInsertUndo"/>
	<Test Action="TextInput.TableInsertRefusedInMarkdown"/>
	<Test Action="TextInput.TableRowsAndColumns"/>
	<Test Action="TextInput.TableTabAddsRow"/>
	<Test Action="TextInput.TableListInCell"/>
	<Test Action="TextInput.TableResizeColumn"/>
	<Test Action="TextInput.TableColumnSpan"/>
	<Test Action="TextInput.TableRules"/>
	<Test Action="TextInput.CodeColoursAndOverflow"/>
	<Test Action="TextInput.PictureEditUndo"/>
	<Test Action="TextInput.PictureRoundTrip"/>
	<Test Action="TextInput.PictureResize"/>
	<Test Action="TextInput.PictureHandlesDraw"/>
	<Test Action="TextInput.PictureWrapLayout"/>
	<Test Action="TextInput.PictureFloatEdit"/>
	<Test Action="TextInput.PictureWrapDraws"/>
	<Test Action="TextInput.PictureTightLayout"/>
	<Test Action="TextInput.PictureFloatMove"/>
	<Test Action="TextInput.PictureTightDraws"/>
	<Test Action="TextInput.PictureRotateRoundTrip"/>
	<Test Action="TextInput.PictureRotateInline"/>
	<Test Action="TextInput.PictureRotateLayout"/>
	<Test Action="TextInput.PictureRotateDraws"/>
	<Test Action="TextInput.PictureRotate"/>
	<Test Action="TextInput.PictureInline"/>
	<Test Action="TextInput.MarkdownPrefixes"/>
	<Test Action="TextInput.MarkdownInline"/>
	<Test Action="TextInput.CodeBlockEditing"/>
	<Test Action="TextInput.RuleEditing"/>
	<Test Action="TextInput.MarkdownBlocksRoundTrip"/>
	<Test Action="TextInput.MarkdownSkipsPlainText"/>
	<Test Action="TextInput.AlignLines"/>
	<Test Action="TextInput.JustifyLines"/>
	<Test Action="TextInput.PageNumbersAndUndo"/>
	<Test Action="TextInput.AlignAroundPicture"/>
	<Test Action="TextInput.MarkdownBlocksDraw"/>
	<Test Action="TextInput.MarkdownFences"/>
	<Test Action="TextInput.CodeBlockTab"/>
	<Test Action="TextInput.MarkdownFancyLists"/>
	<Test Action="TextInput.ListStartNumbers"/>
	<Test Action="TextInput.HeaderFieldTakesPress"/>
	<Test Action="TextInput.ViewStateRoundTrip"/>
	<Test Action="TextInput.FrontmatterKeys"/>
	<Test Action="TextInput.TabStops"/>
	<Test Action="TextInput.SessionScopeSwap"/>
	<Test Action="TextInput.ReadOnlyRefusesEdits"/>
	<Test Action="TextInput.MathRoundTrip"/>
	<Test Action="TextInput.MathLineBox"/>
	<Test Action="TextInput.MathCopyText"/>
	<Test Action="TextInput.MathDraws"/>
	<Test Action="TextInput.MathArrays"/>
	<Test Action="TextInput.MathInsertCommit"/>
	<Test Action="TextInput.MathInsertCancel"/>
	<Test Action="TextInput.MathEditUndo"/>
	<Test Action="TextInput.MathLivePreview"/>
	<Test Action="TextInput.MathEscReverts"/>
	<Test Action="TextInput.MathClickSelects"/>
	<Test Action="TextInput.MathDoubleClickOpens"/>
	<Test Action="Tex.SourceEnterPaste"/>
	<Test Action="Tex.SourceColours"/>
</TestSuite>

=== NexerG/Project-Aurora/AuroraEngine/Data/XML/Documents/Tests/Svg.tests.xml
<?xml version="1.0" encoding="utf-8" ?>
<TestSuite xmlns="http://arctisaurora/AuroraTestTypes"
		  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		  xsi:schemaLocation="http://arctisaurora/AuroraTestTypes ../../Schemas/TestTypeSchema.xsd" >
	<Test Action="Svg.InheritedFill"/>
	<Test Action="Svg.Unrendered"/>
	<Test Action="Svg.Transform"/>
	<Test Action="Svg.Malformed"/>
	<Test Action="Svg.FillRule"/>
	<Test Action="Svg.Arc"/>
	<Test Action="Svg.Shapes"/>
	<Test Action="Svg.StrokeRuns"/>
	<Test Action="Svg.StrokeBake"/>
</TestSuite>

=== NexerG/Project-Aurora/Thorium/Data/XML/Documents/Tests/LatinModern.tests.xml
<?xml version="1.0" encoding="utf-8" ?>
<TestSuite xmlns="http://arctisaurora/AuroraTestTypes"
		  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		  xsi:schemaLocation="http://arctisaurora/AuroraTestTypes ../../Schemas/TestTypeSchema.xsd" >
	<Test Action="LatinModern.Baked"/>
	<Test Action="LatinModern.Draws"/>
	<Test Action="Tex.Preview"/>
	<Test Action="Tex.Floats"/>
	<Test Action="Tex.SplitView.Recompile"/>
	<Test Action="Tex.SplitView.Errors"/>
	<Test Action="Tex.SplitView.ClickToSource"/>
</TestSuite>

=== NexerG/Project-Aurora/Thorium/Data/XML/Documents/Tests/Ribbon.tests.xml
<?xml version="1.0" encoding="utf-8" ?>
<TestSuite xmlns="http://arctisaurora/AuroraTestTypes"
		  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		  xsi:schemaLocation="http://arctisaurora/AuroraTestTypes ../../Schemas/TestTypeSchema.xsd" >
	<Test Action="Ribbon.Shows"/>
	<Test Action="Ribbon.Docs"/>
	<Test Action="Ribbon.Sheets"/>
	<Test Action="Inspector.Docs"/>
	<Test Action="Inspector.Sheets"/>
	<Test Action="Ribbon.Session"/>
	<Test Action="Note.NumbersToggle"/>
	<Test Action="Note.TasksToggle"/>
	<Test Action="Note.InsertPictureFile"/>
	<Test Action="Sheet.ImportCsv"/>
	<Test Action="Ribbon.CsvEntries"/>
</TestSuite>

=== NexerG/Project-Aurora/Thorium/Data/XML/Documents/Tests/Workspace.tests.xml
<?xml version="1.0" encoding="utf-8" ?>
<TestSuite xmlns="http://arctisaurora/AuroraTestTypes"
		  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		  xsi:schemaLocation="http://arctisaurora/AuroraTestTypes ../../Schemas/TestTypeSchema.xsd" >
	<Test Action="Workspace.Switch"/>
	<Test Action="Workspace.Menu"/>
	<Test Action="Workspace.SessionRoundTrip"/>
	<Test Action="Workspace.LegacySession"/>
	<Test Action="Workspace.Reorder"/>
	<Test Action="Workspace.MoveAcross"/>
	<Test Action="Workspace.TearOff"/>
	<Test Action="Workspace.Reset"/>
</TestSuite>

=== NexerG/Project-Aurora/AuroraEngine/Data/XML/Documents/Tests/Math.tests.xml
<?xml version="1.0" encoding="utf-8" ?>
<TestSuite xmlns="http://arctisaurora/AuroraTestTypes"
		  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		  xsi:schemaLocation="http://arctisaurora/AuroraTestTypes ../../Schemas/TestTypeSchema.xsd" >
	<Test Action="Math.SymbolsInCharset"/>
	<Test Action="Math.ParseNeverThrows"/>
	<Test Action="Math.SuperscriptRaises"/>
	<Test Action="Math.SubscriptBelowBaseline"/>
	<Test Action="Math.FractionOnAxis"/>
	<Test Action="Math.BigOpDisplay"/>
	<Test Action="Math.DelimitersGrow"/>
	<Test Action="Math.SqrtCoversBody"/>
	<Test Action="Math.Spacing"/>
	<Test Action="Math.Classes"/>
</TestSuite>

=== NexerG/Project-Aurora/AuroraEngine/Data/XML/Documents/Tests/Tex.tests.xml
<?xml version="1.0" encoding="utf-8" ?>
<TestSuite xmlns="http://arctisaurora/AuroraTestTypes"
		  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		  xsi:schemaLocation="http://arctisaurora/AuroraTestTypes ../../Schemas/TestTypeSchema.xsd" >
	<Test Action="Tex.SourceRoundTrip"/>
	<Test Action="Tex.Catcodes"/>
	<Test Action="Tex.DelimitedDef"/>
	<Test Action="Tex.ExpandAfter"/>
	<Test Action="Tex.Edef"/>
	<Test Action="Tex.Groups"/>
	<Test Action="Tex.Conditionals"/>
	<Test Action="Tex.Registers"/>
	<Test Action="Tex.NewCommand"/>
	<Test Action="Tex.NewEnvironment"/>
	<Test Action="Tex.Errors"/>
	<Test Action="Tex.StepCounter"/>
	<Test Action="Tex.EmFromFont"/>
	<Test Action="Tex.Typeset.Paragraphs"/>
	<Test Action="Tex.Typeset.Fonts"/>
	<Test Action="Tex.Typeset.Sections"/>
	<Test Action="Tex.Typeset.Lists"/>
	<Test Action="Tex.Typeset.Math"/>
	<Test Action="Tex.Typeset.Ligatures"/>
	<Test Action="Tex.Typeset.Accents"/>
	<Test Action="Tex.Typeset.Verbatim"/>
	<Test Action="Tex.Typeset.Errors"/>
	<Test Action="Tex.Lowering"/>
	<Test Action="Tex.Lowering.Lines"/>
	<Test Action="Tex.Typeset.Tabular"/>
	<Test Action="Tex.Typeset.Floats"/>
	<Test Action="Tex.Refs"/>
	<Test Action="Tex.Equations"/>
	<Test Action="Tex.MathEnvironments"/>
	<Test Action="Tex.Bib"/>
	<Test Action="Tex.Lowering.Table"/>
	<Test Action="Tex.Lowering.Image"/>
	<Test Action="Tex.OptimalBreaks"/>
	<Test Action="Tex.JustifyBeforeDisplay"/>
	<Test Action="Tex.Hyphenator"/>
	<Test Action="Tex.SoftHyphen"/>
	<Test Action="Tex.Lowering.Hyphens"/>
	<Test Action="Tex.Lowering.Spacing"/>
	<Test Action="Tex.BlockSpacing"/>
	<Test Action="Tex.Lowering.Pages"/>
	<Test Action="Tex.PageBreak"/>
	<Test Action="Tex.RunningHeads"/>
	<Test Action="Tex.Lowering.Footnote"/>
	<Test Action="Tex.Footnotes"/>
	<Test Action="Tex.Lowering.Float"/>
	<Test Action="Tex.FloatPlacement"/>
</TestSuite>

=== NexerG/Project-Aurora/Thorium/Data/XML/Documents/Tests/Planner.tests.xml
<?xml version="1.0" encoding="utf-8" ?>
<TestSuite xmlns="http://arctisaurora/AuroraTestTypes"
		  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		  xsi:schemaLocation="http://arctisaurora/AuroraTestTypes ../../Schemas/TestTypeSchema.xsd" >
	<Test Action="Planner.XmlRoundTrip"/>
	<Test Action="Planner.GanttGeometry"/>
	<Test Action="Planner.BoardColumns"/>
	<Test Action="Planner.ViewState"/>
	<Test Action="Planner.DragMoveUndo"/>
	<Test Action="Planner.DragResize"/>
	<Test Action="Planner.EditAddDelete"/>
	<Test Action="Planner.DeleteKeys"/>
	<Test Action="Planner.SaveKey"/>
	<Test Action="Planner.PopupCategory"/>
	<Test Action="Planner.MenuMove"/>	<Test Action="Planner.GanttGolden"/>
	<Test Action="Planner.BoardDragAcross"/>
	<Test Action="Planner.BoardDragWithin"/>
	<Test Action="Planner.BoardGolden"/>
	<Test Action="Planner.CategoryEdits"/>
	<Test Action="Planner.CategoryPopup"/>
	<Test Action="Planner.AssigneeGolden"/>
	<Test Action="Planner.CalendarPack"/>
	<Test Action="Planner.CalendarGeometry"/>
	<Test Action="Planner.CalendarSnap"/>
	<Test Action="Planner.WeekStart"/>
	<Test Action="Planner.CalendarDragUndo"/>
	<Test Action="Planner.CalendarCreate"/>
	<Test Action="Planner.CalendarMonth"/>
	<Test Action="Planner.CalendarGolden"/>
	<Test Action="Planner.FollowersMove"/>
	<Test Action="Planner.FollowCycle"/>
	<Test Action="Planner.AttachmentText"/>
	<Test Action="Planner.Description"/>
	<Test Action="Planner.ExpandBoard"/>
	<Test Action="Planner.ExpandGantt"/>
	<Test Action="Planner.ExpandCalendar"/>
	<Test Action="Planner.AttachmentGolden"/>
	<Test Action="Planner.TwoViews"/>
	<Test Action="Planner.WheelZoom"/>
</TestSuite>
