=== NexerG/Project-Aurora/Periodic/Data/XML/Schemas/InputTypeSchema.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:types="http://arctisaurora/AuroraInputTypes" xmlns:actions="http://arctisaurora/ActionDependencies" xmlns:allTypes="http://arctisaurora/AuroraTypes" elementFormDefault="qualified" targetNamespace="http://arctisaurora/AuroraInputTypes" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:import schemaLocation="actionSchema.xsd" namespace="http://arctisaurora/ActionDependencies" />
  <xs:import schemaLocation="AllTypesSchema.xsd" namespace="http://arctisaurora/AuroraTypes" />
  <xs:simpleType name="Input">
    <xs:union memberTypes="types:InputModifier types:KeybindAccess types:Keys" />
  </xs:simpleType>
  <xs:element name="KeybindModifier" type="types:KeybindModifier" />
  <xs:complexType name="KeybindModifier">
    <xs:sequence />
    <xs:attribute name="Key" type="types:Keys" />
  </xs:complexType>
  <xs:simpleType name="InputModifier">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Extend" />
    </xs:restriction>
  </xs:simpleType>
  <xs:element name="NamedModifier" type="types:NamedModifier" />
  <xs:complexType name="NamedModifier">
    <xs:sequence />
    <xs:attribute name="Modifier" type="types:InputModifier" />
    <xs:attribute name="Key" type="types:Keys" />
  </xs:complexType>
  <xs:simpleType name="KeybindAccess">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Open" />
      <xs:enumeration value="Locked" />
    </xs:restriction>
  </xs:simpleType>
  <xs:element name="Keybind" type="types:Keybind" />
  <xs:complexType name="Keybind">
    <xs:sequence>
      <xs:element minOccurs="0" maxOccurs="unbounded" name="Modifier" type="types:KeybindModifier">
        <xs:annotation>
          <xs:documentation></xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element name="KeybindModifier" type="types:KeybindModifier" />
        <xs:element name="Condition" type="types:Condition" />
        <xs:element name="Press" type="types:Press" />
        <xs:element name="Release" type="types:Release" />
        <xs:element name="Hold" type="types:Hold" />
        <xs:element name="HoldRelease" type="types:HoldRelease" />
        <xs:element name="MaxHoldTime" type="types:MaxHoldTime" />
        <xs:element name="MultiTap" type="types:MultiTap" />
        <xs:element name="Continuous" type="types:Continuous" />
        <xs:element name="Repeat" type="types:Repeat" />
        <xs:element name="Toggle" type="types:Toggle" />
        <xs:element name="HoldContinuous" type="types:HoldContinuous" />
        <xs:element name="Chord" type="types:Chord" />
      </xs:choice>
    </xs:sequence>
    <xs:attribute name="Trigger" type="types:Keys" />
    <xs:attribute name="Action" type="actions:Input" />
    <xs:attribute name="Access" type="types:KeybindAccess" />
  </xs:complexType>
  <xs:simpleType name="Keys">
    <xs:restriction base="xs:string">
      <xs:enumeration value="A" />
      <xs:enumeration value="B" />
      <xs:enumeration value="C" />
      <xs:enumeration value="D" />
      <xs:enumeration value="E" />
      <xs:enumeration value="F" />
      <xs:enumeration value="G" />
      <xs:enumeration value="H" />
      <xs:enumeration value="I" />
      <xs:enumeration value="J" />
      <xs:enumeration value="K" />
      <xs:enumeration value="L" />
      <xs:enumeration value="M" />
      <xs:enumeration value="N" />
      <xs:enumeration value="O" />
      <xs:enumeration value="P" />
      <xs:enumeration value="Q" />
      <xs:enumeration value="R" />
      <xs:enumeration value="S" />
      <xs:enumeration value="T" />
      <xs:enumeration value="U" />
      <xs:enumeration value="V" />
      <xs:enumeration value="W" />
      <xs:enumeration value="X" />
      <xs:enumeration value="Y" />
      <xs:enumeration value="Z" />
      <xs:enumeration value="Apostrophe" />
      <xs:enumeration value="Comma" />
      <xs:enumeration value="Minus" />
      <xs:enumeration value="Period" />
      <xs:enumeration value="Slash" />
      <xs:enumeration value="Semicolon" />
      <xs:enumeration value="Equal" />
      <xs:enumeration value="LeftBracket" />
      <xs:enumeration value="Backslash" />
      <xs:enumeration value="RightBracket" />
      <xs:enumeration value="GraveAccent" />
      <xs:enumeration value="Numpad0" />
      <xs:enumeration value="Numpad1" />
      <xs:enumeration value="Numpad2" />
      <xs:enumeration value="Numpad3" />
      <xs:enumeration value="Numpad4" />
      <xs:enumeration value="Numpad5" />
      <xs:enumeration value="Numpad6" />
      <xs:enumeration value="Numpad7" />
      <xs:enumeration value="Numpad8" />
      <xs:enumeration value="Numpad9" />
      <xs:enumeration value="NumpadDecimal" />
      <xs:enumeration value="NumpadDivide" />
      <xs:enumeration value="NumpadMultiply" />
      <xs:enumeration value="NumpadSubtract" />
      <xs:enumeration value="NumpadAdd" />
      <xs:enumeration value="NumpadEnter" />
      <xs:enumeration value="NumpadEqual" />
      <xs:enumeration value="Num0" />
      <xs:enumeration value="Num1" />
      <xs:enumeration value="Num2" />
      <xs:enumeration value="Num3" />
      <xs:enumeration value="Num4" />
      <xs:enumeration value="Num5" />
      <xs:enumeration value="Num6" />
      <xs:enumeration value="Num7" />
      <xs:enumeration value="Num8" />
      <xs:enumeration value="Num9" />
      <xs:enumeration value="Space" />
      <xs:enumeration value="Enter" />
      <xs:enumeration value="Tab" />
      <xs:enumeration value="AnySymbol" />
      <xs:enumeration value="Backspace" />
      <xs:enumeration value="Escape" />
      <xs:enumeration value="LeftControl" />
      <xs:enumeration value="RightControl" />
      <xs:enumeration value="LeftShift" />
      <xs:enumeration value="RightShift" />
      <xs:enumeration value="LeftWin" />
      <xs:enumeration value="RightWin" />
      <xs:enumeration value="Menu" />
      <xs:enumeration value="CapsLock" />
      <xs:enumeration value="ScrollLock" />
      <xs:enumeration value="NumLock" />
      <xs:enumeration value="PrintScreen" />
      <xs:enumeration value="Pause" />
      <xs:enumeration value="LeftAlt" />
      <xs:enumeration value="RightAlt" />
      <xs:enumeration value="LeftSuper" />
      <xs:enumeration value="RightSuper" />
      <xs:enumeration value="Up" />
      <xs:enumeration value="Down" />
      <xs:enumeration value="Left" />
      <xs:enumeration value="Right" />
      <xs:enumeration value="Home" />
      <xs:enumeration value="End" />
      <xs:enumeration value="PageUp" />
      <xs:enumeration value="PageDown" />
      <xs:enumeration value="Insert" />
      <xs:enumeration value="Delete" />
      <xs:enumeration value="F1" />
      <xs:enumeration value="F2" />
      <xs:enumeration value="F3" />
      <xs:enumeration value="F4" />
      <xs:enumeration value="F5" />
      <xs:enumeration value="F6" />
      <xs:enumeration value="F7" />
      <xs:enumeration value="F8" />
      <xs:enumeration value="F9" />
      <xs:enumeration value="F10" />
      <xs:enumeration value="F11" />
      <xs:enumeration value="F12" />
      <xs:enumeration value="F13" />
      <xs:enumeration value="F14" />
      <xs:enumeration value="F15" />
      <xs:enumeration value="F16" />
      <xs:enumeration value="F17" />
      <xs:enumeration value="F18" />
      <xs:enumeration value="F19" />
      <xs:enumeration value="F20" />
      <xs:enumeration value="F21" />
      <xs:enumeration value="F22" />
      <xs:enumeration value="F23" />
      <xs:enumeration value="F24" />
      <xs:enumeration value="F25" />
      <xs:enumeration value="MouseLeft" />
      <xs:enumeration value="MouseRight" />
      <xs:enumeration value="MouseMiddle" />
      <xs:enumeration value="MouseButton4" />
      <xs:enumeration value="MouseButton5" />
      <xs:enumeration value="MouseButton6" />
      <xs:enumeration value="MouseButton7" />
      <xs:enumeration value="MouseButton8" />
      <xs:enumeration value="unknown" />
    </xs:restriction>
  </xs:simpleType>
  <xs:element name="KeybindMap" type="types:KeybindMap" />
  <xs:complexType name="KeybindMap">
    <xs:sequence>
      <xs:element minOccurs="0" maxOccurs="unbounded" name="Keybind" type="types:Keybind">
        <xs:annotation>
          <xs:documentation></xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element minOccurs="0" maxOccurs="unbounded" name="NamedModifier" type="types:NamedModifier">
        <xs:annotation>
          <xs:documentation></xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element name="NamedModifier" type="types:NamedModifier" />
        <xs:element name="Keybind" type="types:Keybind" />
      </xs:choice>
    </xs:sequence>
  </xs:complexType>
  <xs:element name="Condition" type="types:Condition" />
  <xs:complexType name="Condition">
    <xs:sequence />
  </xs:complexType>
  <xs:element name="Press" type="types:Press" />
  <xs:complexType name="Press">
    <xs:sequence />
  </xs:complexType>
  <xs:element name="Release" type="types:Release" />
  <xs:complexType name="Release">
    <xs:sequence />
  </xs:complexType>
  <xs:element name="Hold" type="types:Hold" />
  <xs:complexType name="Hold">
    <xs:sequence />
    <xs:attribute name="Threshold" type="xs:float" />
  </xs:complexType>
  <xs:element name="HoldRelease" type="types:HoldRelease" />
  <xs:complexType name="HoldRelease">
    <xs:sequence />
    <xs:attribute name="Threshold" type="xs:float" />
  </xs:complexType>
  <xs:element name="MaxHoldTime" type="types:MaxHoldTime" />
  <xs:complexType name="MaxHoldTime">
    <xs:sequence />
    <xs:attribute name="Threshold" type="xs:float" />
  </xs:complexType>
  <xs:element name="MultiTap" type="types:MultiTap" />
  <xs:complexType name="MultiTap">
    <xs:sequence />
    <xs:attribute name="Count" type="xs:int" />
  </xs:complexType>
  <xs:element name="Continuous" type="types:Continuous" />
  <xs:complexType name="Continuous">
    <xs:sequence />
  </xs:complexType>
  <xs:element name="Repeat" type="types:Repeat" />
  <xs:complexType name="Repeat">
    <xs:sequence />
  </xs:complexType>
  <xs:element name="Toggle" type="types:Toggle" />
  <xs:complexType name="Toggle">
    <xs:sequence />
  </xs:complexType>
  <xs:element name="HoldContinuous" type="types:HoldContinuous" />
  <xs:complexType name="HoldContinuous">
    <xs:sequence />
    <xs:attribute name="Threshold" type="xs:float" />
  </xs:complexType>
  <xs:element name="Chord" type="types:Chord" />
  <xs:complexType name="Chord">
    <xs:sequence />
    <xs:attribute name="Key" type="types:Keys" />
  </xs:complexType>
</xs:schema>

=== NexerG/Project-Aurora/Periodic/Data/XML/Documents/Inputs/InputMap.xml
<?xml version="1.0" encoding="utf-8" ?>
<KeybindMap xmlns="http://arctisaurora/AuroraInputTypes"
		  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		  xsi:schemaLocation="http://arctisaurora/AuroraInputTypes ../../Schemas/InputTypeSchema.xsd" >
	<NamedModifier Modifier="Extend" Key="LeftShift" />
	<NamedModifier Modifier="Extend" Key="RightShift" />

	<Keybind Trigger="Backspace" Action="ExitApplication">
		<Modifier Key="LeftControl" />
		<Press />
	</Keybind>

	<Keybind Trigger="AnySymbol" Action="Text.Write">
		<Continuous />
	</Keybind>

	<Keybind Trigger="Backspace" Action="Text.Backspace">
		<Repeat />
	</Keybind>

	<Keybind Trigger="Delete" Action="Text.Delete">
		<Repeat />
	</Keybind>

	<Keybind Trigger="Enter" Action="Text.NewBlock">
		<Repeat />
	</Keybind>

	<Keybind Trigger="Escape" Action="Text.Cancel">
		<Press />
	</Keybind>

	<Keybind Trigger="S" Action="Text.Save">
		<Modifier Key="LeftControl" />
		<Press />
	</Keybind>

	<Keybind Trigger="Z" Action="Text.Undo">
		<Modifier Key="LeftControl" />
		<Press />
	</Keybind>

	<Keybind Trigger="Y" Action="Text.Redo">
		<Modifier Key="LeftControl" />
		<Press />
	</Keybind>

	<Keybind Trigger="Left" Action="Text.CaretLeft">
		<Repeat />
	</Keybind>

	<Keybind Trigger="Right" Action="Text.CaretRight">
		<Repeat />
	</Keybind>

	<Keybind Trigger="Up" Action="Text.CaretUp">
		<Repeat />
	</Keybind>

	<Keybind Trigger="Down" Action="Text.CaretDown">
		<Repeat />
	</Keybind>

	<Keybind Trigger="Home" Action="Text.CaretLineStart">
		<Press />
	</Keybind>

	<Keybind Trigger="End" Action="Text.CaretLineEnd">
		<Press />
	</Keybind>

	<Keybind Trigger="PageUp" Action="Text.CaretPageUp">
		<Repeat />
	</Keybind>

	<Keybind Trigger="PageDown" Action="Text.CaretPageDown">
		<Repeat />
	</Keybind>

	<!-- the two-modifier bind is declared first: IsShadowed only suppresses the looser bind once the
	     stricter one has already fired this pass -->
	<Keybind Trigger="Backslash" Action="View.SplitDown">
		<Modifier Key="LeftControl" />
		<Modifier Key="LeftShift" />
		<Press />
	</Keybind>

	<Keybind Trigger="Backslash" Action="View.SplitRight">
		<Modifier Key="LeftControl" />
		<Press />
	</Keybind>

</KeybindMap>
