=== NexerG/Project-Aurora/AuroraEngine/Data/XML/Schemas/DataPoolsTypeSchema.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:types="http://arctisaurora/AuroraDataPoolsTypes" xmlns:actions="http://arctisaurora/ActionDependencies" xmlns:allTypes="http://arctisaurora/AuroraTypes" elementFormDefault="qualified" targetNamespace="http://arctisaurora/AuroraDataPoolsTypes" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:import schemaLocation="actionSchema.xsd" namespace="http://arctisaurora/ActionDependencies" />
  <xs:import schemaLocation="AllTypesSchema.xsd" namespace="http://arctisaurora/AuroraTypes" />
  <xs:simpleType name="DataPools">
    <xs:union memberTypes="types:PoolGrowthType" />
  </xs:simpleType>
  <xs:element name="GpuTransform" type="types:GpuTransform" />
  <xs:complexType name="GpuTransform">
    <xs:sequence />
  </xs:complexType>
  <xs:simpleType name="PoolGrowthType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Multiplicative" />
      <xs:enumeration value="Additive" />
    </xs:restriction>
  </xs:simpleType>
  <xs:element name="Component" type="types:Component" />
  <xs:complexType name="Component">
    <xs:sequence />
    <xs:attribute name="Type" type="allTypes:Uncategorized" />
  </xs:complexType>
  <xs:element name="Pool" type="types:Pool" />
  <xs:complexType name="Pool">
    <xs:sequence>
      <xs:element minOccurs="0" maxOccurs="unbounded" name="Component" type="types:Component">
        <xs:annotation>
          <xs:documentation></xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
    <xs:attribute name="Name" type="xs:string" />
    <xs:attribute name="System" type="xs:string" />
    <xs:attribute name="Capacity" type="xs:int" />
    <xs:attribute name="Ordered" type="xs:boolean" />
    <xs:attribute name="SortAction" type="xs:string" />
    <xs:attribute name="Growth" type="types:PoolGrowthType" />
    <xs:attribute name="GrowthValue" type="xs:int" />
  </xs:complexType>
  <xs:element name="EnginePools" type="types:EnginePools" />
  <xs:complexType name="EnginePools">
    <xs:sequence>
      <xs:element minOccurs="0" maxOccurs="unbounded" name="Pool" type="types:Pool">
        <xs:annotation>
          <xs:documentation></xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:element name="TransformData" type="types:TransformData" />
  <xs:complexType name="TransformData">
    <xs:sequence />
  </xs:complexType>
</xs:schema>

=== NexerG/Project-Aurora/AuroraEngine/Data/XML/Documents/Pools.pools.xml
<EnginePools xmlns="http://arctisaurora/AuroraDataPoolsTypes"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="http://arctisaurora/AuroraDataPoolsTypes ../Schemas/DataPoolsTypeSchema.xsd">

	<Pool Name="UIElements" Capacity="1024" Ordered="true" SortAction="UI.ElementOrder" Growth="Multiplicative" GrowthValue="2">
		<Component Type="ArrangeData"/>
		<Component Type="LayoutNode"/>
		<Component Type="VulkanControl"/>
	</Pool>

	<Pool Name="UIQuads" Capacity="1024" Ordered="false" Growth="Multiplicative" GrowthValue="2" Handles="false">
		<Component Type="ControlGeometry"/>
		<Component Type="VulkanControl"/>
	</Pool>

	<Pool Name="Entities" Capacity="1024" Ordered="false" Growth="Multiplicative" GrowthValue="2">
		<Component Type="TransformData"/>
	</Pool>

	<Pool Name="Paints" Capacity="1024" Ordered="false" Growth="Multiplicative" GrowthValue="2" Handles="false">
		<Component Type="GpuPaint"/>
	</Pool>

	<Pool Name="Gradients" Capacity="32" Ordered="false" Growth="Additive" GrowthValue="32" Handles="false">
		<Component Type="GpuGradient"/>
	</Pool>

	<Pool Name="Effects" Capacity="32" Ordered="false" Growth="Additive" GrowthValue="32" Handles="false">
		<Component Type="GpuEffect"/>
	</Pool>

	<Pool Name="Animations" Capacity="256" Ordered="false" Growth="Multiplicative" GrowthValue="2" Handles="false">
		<Component Type="AnimationTrack"/>
		<Component Type="TweenParams"/>
		<Component Type="KeyParams"/>
		<Component Type="SpringParams"/>
		<Component Type="TrackCold"/>
	</Pool>

	<Pool Name="Signals" Capacity="64" Ordered="false" Growth="Multiplicative" GrowthValue="2" Handles="false">
		<Component Type="SignalValue"/>
		<Component Type="SignalLife"/>
	</Pool>

	<Pool Name="Keyframes" Capacity="256" Ordered="false" Growth="Multiplicative" GrowthValue="2" Handles="false">
		<Component Type="Keyframe"/>
	</Pool>

	<Pool Name="LayoutDirty" Capacity="256" Ordered="false" Growth="Multiplicative" GrowthValue="2" Handles="false">
		<Component Type="DirtyLayout"/>
	</Pool>

	<Pool Name="AnimationDone" Capacity="64" Ordered="false" Growth="Multiplicative" GrowthValue="2" Handles="false">
		<Component Type="FinishedTrack"/>
	</Pool>

	<Pool Name="AnimationBindings" Capacity="256" Ordered="false" Growth="Multiplicative" GrowthValue="2" Handles="false">
		<Component Type="TrackBinding"/>
	</Pool>

	<Pool Name="AnimationAwake" Capacity="256" Ordered="false" Growth="Multiplicative" GrowthValue="2" Handles="false">
		<Component Type="AwakeTrack"/>
	</Pool>

	<Pool Name="PaintFades" Capacity="64" Ordered="false" Growth="Multiplicative" GrowthValue="2" Handles="false">
		<Component Type="SlotFade"/>
	</Pool>

</EnginePools>
